title: 琳琳的博客
email: "linlinblogs@sina.com"
description: "记录工作和生活中学习或复习的知识。"
baseurl: "/"
url: "https://iamlinlin.fun"
twitter_username: "linlin"
github_username:  "linlin"

# Build settings
theme: minima
plugins:
  - jekyll-feed

#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
